/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

ALTER TABLE `users` ADD COLUMN `kills`  int(3) NULL DEFAULT 0;
ALTER TABLE `users` ADD COLUMN `deaths`  int(3) NULL DEFAULT 0;
ALTER TABLE `users` ADD COLUMN `level`  int(3) NOT NULL DEFAULT 0;
ALTER TABLE `users` ADD COLUMN `rp`  int(5) NOT NULL DEFAULT 0;
ALTER TABLE `users` ADD COLUMN `timePlay`  int(100) NOT NULL DEFAULT 0;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
